



file:
  img:
    path: /my-mall-img/
  real:
    path: /root/my-management-img/
  mimg:
    path: /my-management-img/


#/Users/mac/大学学习整理/java/managementplatform2/target/my-management-img/
jwt:
  secret: my-mall
  expiration: 604800


# 设置开发环境的配置文件
#  profiles:
#    active: dev


#  参考： https://www.cnblogs.com/raphael5200/p/9891155.html
#
#
## 配置mybatis的全局映射文件
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml # 指定全局配置文件的位置
#  mapper-locations: classpath:mybatis/mapper/*.xml # 指定sql映射文件的位置，*是包括所有的
#  type-aliases-package: com.tapd.entities # MyBatis注解形式扫描实体类路径







