# jdbc连接mysql  -- 开发
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://47.97.184.36:3306/mail
    driver-class-name: com.mysql.cj.jdbc.Driver
  # https://blog.csdn.net/weixin_42992109/article/details/88412540
  # 发送邮件
  mail:
    host: smtp.qq.com
    port: 465
    username: waniiu@126.com
    password: qq 邮箱生成的授权码***(下文介绍如何获取)***
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true #一定要开启ssl,不然会503 验证失败的

 # 设置开发环境的配置文件
#  profiles:
#    active: dev


#  参考： https://www.cnblogs.com/raphael5200/p/9891155.html
#
#
## 配置mybatis的全局映射文件
#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml # 指定全局配置文件的位置
#  mapper-locations: classpath:mybatis/mapper/*.xml # 指定sql映射文件的位置，*是包括所有的
#  type-aliases-package: com.tapd.entities # MyBatis注解形式扫描实体类路径

file:
  img:
    path: /my-mail-img/

jwt:
  secret: my-mail
  expiration: 648000







